#!/bin/sh
#-
# Copyright (c) 2024 Jessica Clarke
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

set -e
set -u

die() {
	echo >&2 "$@"
	exit 1
}

usage() {
	die "Usage: $0 <file>"
}

if [ $# -ne 1 ]; then
	usage
fi

if [ -z "${GIT_REBASE_FIRST_PARENT_UPSTREAM:-}" ]; then
	die "GIT_REBASE_FIRST_PARENT_UPSTREAM is not set"
fi

if [ -z "${GIT_REBASE_FIRST_PARENT_BRANCH:-}" ]; then
	die "GIT_REBASE_FIRST_PARENT_BRANCH is not set"
fi

TMPFILE="`mktemp`"
{ rm "$TMPFILE" && cat <"$1" && make-rebase-first-parent "$GIT_REBASE_FIRST_PARENT_UPSTREAM" "$GIT_REBASE_FIRST_PARENT_BRANCH" >"$1"; } <"$TMPFILE" >"$TMPFILE"
if [ -n "${GIT_REBASE_FIRST_PARENT_SEQUENCE_EDITOR:+set}" ]; then
	sh -c "$GIT_REBASE_FIRST_PARENT_SEQUENCE_EDITOR \"\$@\"" "$GIT_REBASE_FIRST_PARENT_SEQUENCE_EDITOR" "$1"
fi
