#!/bin/sh
#-
# Copyright (c) 2024 Jessica Clarke
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

set -e
set -u

die() {
	echo >&2 "$@"
	exit 1
}

usage() {
	die "Usage: $0 <upstream> <branch>"
}

if [ $# -ne 2 ]; then
	usage
fi

git log --first-parent --reverse --format='tformat:%H %P#%s' "$1".."$2" | while read -r l; do
	s="${l#*#}"
	l="${l%%#*}"
	c="${l%% *}"
	p="${l#* }"
	p="$(echo "$p" | sed 's/^[[:space:]]*[^[:space:]]\{1,\}//;s/[[:space:]]*\([^[:space:]]\{1,\}\)/ -p \1/g')"
	if [ -z "$p" ]; then
		printf 'pick %s %s\n' "$c" "$s"
	else
		printf '# %s\n' "$s"
		echo "exec git update-ref HEAD \`git commit-tree -p HEAD$p -m 'dummy merge for $c' 'HEAD^{tree}'\` && git cherry-pick -n -m 1 $c && git commit --amend -q -n -C $c"
	fi
	if [ -n "${GIT_REBASE_FIRST_PARENT_EXEC_CMDS}" ]; then
		printf "%b" "${GIT_REBASE_FIRST_PARENT_EXEC_CMDS}"
	fi
done

sed '/^noop$/d'
